project:
  type: website
  output-dir: docs

website:
  title: "elisa kaori"
  navbar:
    left:
      - href: index.qmd
        text: sobre mim
      - href: experiencia.qmd
        text: experiÃªncia
      - projetos.qmd
  favicon: transferir.jpg

format:
  html:
    theme: cosmo.scss
    css: styles.css
    toc: true
    lang: pt



